apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-kubernetes-operator
  namespace: infra
  labels:
    app.kubernetes.io/name: flink-kubernetes-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flink-kubernetes-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flink-kubernetes-operator
    spec:
      serviceAccountName: flink-kubernetes-operator
      containers:
      - name: flink-kubernetes-operator
        image: apache/flink-kubernetes-operator:1.6.1
        args: ["operator"]
        ports:
        - containerPort: 8080
        env:
        - name: OPERATOR_NAMESPACE
          value: infra
        - name: LOG_LEVEL
          value: INFO
        livenessProbe:
          httpGet:
            path: /health
            port: 8085
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8085
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink-kubernetes-operator
  namespace: infra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flink-kubernetes-operator
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps", "services", "secrets"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["*"]
- apiGroups: ["flink.apache.org"]
  resources: ["flinkdeployments", "flinksessionjobs"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flink-kubernetes-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flink-kubernetes-operator
subjects:
- kind: ServiceAccount
  name: flink-kubernetes-operator
  namespace: infra