apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tethys
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tethys
  template:
    metadata:
      labels:
        app: tethys
    spec:
      containers:
      - name: tethys
        image: tethys:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 18080
        env:
        - name: MYSQL_HOST
          value: "mysql.infra.svc.cluster.local"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USERNAME
          value: "root"
        - name: MYSQL_PASSWORD
          value: "rootpassword"
        - name: FLINK_HOST
          value: "flink-jobmanager.infra.svc.cluster.local"
        - name: FLINK_REST_PORT
          value: "8081"
        - name: FLINK_RPC_PORT
          value: "6123"
        - name: KAFKA_HOST
          value: "kafka.infra.svc.cluster.local"
        - name: KAFKA_PORT
          value: "9092"
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: tethys-service
  namespace: app
spec:
  selector:
    app: tethys
  ports:
    - protocol: TCP
      port: 18080
      targetPort: 18080
  type: LoadBalancer