apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tethys
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tethys
  template:
    metadata:
      labels:
        app: tethys
    spec:
      containers:
      - name: tethys
        image: tethys:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 19080
        env:
        - name: SERVER_PORT
          value: "19080"
        - name: MYSQL_HOST
          value: "mysql.infra.svc.cluster.local"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USERNAME
          value: "root"
        - name: MYSQL_PASSWORD
          value: "rootpassword"
        - name: KAFKA_HOST
          value: "kafka.infra.svc.cluster.local"
        - name: KAFKA_PORT
          value: "9092"
        resources:
          requests:
            memory: "500Mi"
            cpu: "100m"
          limits:
            memory: "800Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: tethys-service
  namespace: app
spec:
  selector:
    app: tethys
  ports:
    - protocol: TCP
      port: 19080
      targetPort: 19080
  type: LoadBalancer